import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth focus:scroll-auto">
      <head>
        <title>Hotel Agency - ilman teguh prasetya</title>
      </head>
      <body className={inter.className}>
        {children}
        <p className="flex justify-center items-center align-middle text-slate-400 text-xs lg:text-base px-4">
          © 2024 Ilman Teguh Prasetya. Created with passion and dedication by
          Ilman Teguh Prasetya.
        </p>
      </body>
    </html>
  );
}
